import { redirect } from "next/navigation";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { OnboardingClient } from "./OnboardingClient";

/**
 * Server-side guard: if the user already has a custom (non-auto-generated) username,
 * they've completed onboarding — send them to their profile instead.
 *
 * Auto-generated usernames always end with _{8 base-36 chars} (from Date.now().toString(36)).
 */
function isAutoGeneratedUsername(username: string): boolean {
  return /_.{8,}$/.test(username);
}

export default async function OnboardingPage() {
  const session = await auth();

  // Must be signed in to reach onboarding
  if (!session?.user) redirect("/login");

  const userId = (session.user as { id?: string }).id;
  if (userId) {
    const dbUser = await prisma.user.findUnique({
      where: { id: userId },
      select: { username: true },
    });
    if (dbUser && !isAutoGeneratedUsername(dbUser.username)) {
      // Already onboarded — go to their profile
      redirect(`/${dbUser.username}`);
    }
  }

  return <OnboardingClient />;
}
